### ISSUE TITLE
Wrong Path to Export getTsconfigPath

### ISSUE THREAD

**Issue by hanihusam** [kodingdotninja/style-guide#1]
## Describe the bug

> A clear and concise description of what the bug is.

This line doesn't exist. It's not exported `getTsconfigPath` function.

```ts
const { getTsconfigPath } = require("@kodingdotninja/style-guide/eslint/helpers");
```

## To Reproduce

1. Go to [Configuring Eslint for TypeScript](https://github.com/kodingdotninja/style-guide#configuring-eslint-for-typescript)
2. Implement it to your `.eslintrc.js` file
3. Execute eslint
4. You'll see the error as in the screenshot below

## Expected behavior

> A clear and concise description of what you expected to happen.

It should export the correct function.

## Screenshots

> If applicable, add screenshots to help explain your problem.

### My Eslint Config

![code](https://github.com/kodingdotninja/style-guide/assets/25399426/56bf7780-6c3a-4855-96a5-cf93eb95a70c)

### The Error

```
Oops! Something went wrong! :(

ESLint: 8.47.0

Error: Cannot read config file: /Users/hanihusam/Dev/curious-me-app-main/.eslintrc.js
Error: Cannot find module '@kodingdotninja/style-guide/eslint/helpers'
Require stack:
- /Users/hanihusam/Dev/curious-me-app-main/.eslintrc.js
- /Users/hanihusam/Dev/curious-me-app-main/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
- /Users/hanihusam/Dev/curious-me-app-main/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/hanihusam/Dev/curious-me-app-main/node_modules/eslint/lib/eslint/eslint.js
- /Users/hanihusam/Dev/curious-me-app-main/node_modules/eslint/lib/eslint/index.js
- /Users/hanihusam/Dev/curious-me-app-main/node_modules/eslint/lib/cli.js
- /Users/hanihusam/Dev/curious-me-app-main/node_modules/eslint/bin/eslint.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/hanihusam/Dev/curious-me-app-main/.eslintrc.js:1:29)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
```

## Additional context

> Add any other context about the problem here.

After that I found the right path which is here `@kodingdotninja/style-guide/eslint/utils/tsconfig`. Is it correct?
However when I implement that path and run the `eslint` I got another error,

```
Oops! Something went wrong! :(

ESLint: 8.47.0

TypeError: Error while loading rule 'react/function-component-definition': `[[GeneratorState]]` is not present on `O`
Occurred while linting /Users/hanihusam/Dev/curious-me-app-main/src/app.tsx
    at Object.assert (/Users/hanihusam/Dev/curious-me-app-main/node_modules/es-iterator-helpers/node_modules/internal-slot/index.js:19:10)
    at GeneratorStart (/Users/hanihusam/Dev/curious-me-app-main/node_modules/es-iterator-helpers/aos/GeneratorStart.js:14:7)
    at CreateIteratorFromClosure (/Users/hanihusam/Dev/curious-me-app-main/node_modules/es-iterator-helpers/aos/CreateIteratorFromClosure.js:45:2)
    at MapIterator.map (/Users/hanihusam/Dev/curious-me-app-main/node_modules/es-iterator-helpers/Iterator.prototype.map/implementation.js:76:15)
    at mergeRules (/Users/hanihusam/Dev/curious-me-app-main/node_modules/eslint-plugin-react/lib/util/Components.js:273:22)
    at Components.componentRule (/Users/hanihusam/Dev/curious-me-app-main/node_modules/eslint-plugin-react/lib/util/Components.js:930:22)
    at createRuleListeners (/Users/hanihusam/Dev/curious-me-app-main/node_modules/eslint/lib/linter/linter.js:870:21)
    at /Users/hanihusam/Dev/curious-me-app-main/node_modules/eslint/lib/linter/linter.js:1040:110
    at Array.forEach (<anonymous>)
    at runRules (/Users/hanihusam/Dev/curious-me-app-main/node_modules/eslint/lib/linter/linter.js:977:34)
```

**Comment by r17x** [comment]
Hi @hanihusam thanks for make a first issue of this project. 

Could you specified `nodejs` version ? 

Thanks

**Comment by grikomsn** [comment]
Hey @hanihusam, thanks for the heads up! Patch incoming. 🙏🏻

**Comment by hanihusam** [comment]
> Hi @hanihusam thanks for make a first issue of this project.
> 
> Could you specified `nodejs` version ?
> 
> Thanks

I am using v18.16.1

**Comment by grikomsn** [comment]
https://github.com/kodingdotninja/style-guide/commit/443b1a5a25c4c1e0de0de9bfa9ff12355b9632e4

**Comment by grikomsn** [comment]
wait my bad lol, updated again at https://github.com/kodingdotninja/style-guide/commit/5c06ac3d4f91c6a0ddfa91baeff2c292c9e24890
